### ISSUE TITLE
Use onMouseOver instead of onMouseEnter

### ISSUE THREAD

**Issue by kgilles** [klarna/higher-order-components#20]
We're using withHoverProps in the Klarna UI FieldTooltip component. When this component is added in a Field that is disabled then the onMouseEnter event isn't always triggered. The user needs to completely move their mouse out of the Field and any parent components before it's triggered again.

I suggest we use onMouseOver instead, or add a new hover component that does, as this event is triggered when hovering over child elements no matter how deep they are.

**Comment by xaviervia** [comment]
Great point! Thanks

**Comment by xaviervia** [comment]
Continues in the PR ( #21 )
