### ISSUE TITLE
Update overridable to a whole new API 

### ISSUE THREAD

**Issue by xaviervia** [klarna/higher-order-components#25]
The `overridable` higher-order component (to be renamed `withOverrideFromContext` or something like that) will be revamped to be way more generic and simpler. The idea is to support an API similar to:

```javascript
import React from 'react'
import {render} from 'react-dom'
import {getContextualizer} from 'react-context-props'
import {withOverrideFromContext} from '@klarna/higher-order-components'

// For Button we will just partially override the style prop
const Button = ({style}) => <button style={style}>Plain button</button>
// For Input we will just replace the implementation
const Input = () => <input type='radio' />

const OverridableButton = withOverrideFromContext(Button)
const OverridableInput = withOverrideFromContext(Input)

const Overrides = getContextualizer({ 
  Button: PropTypes.oneOf([
    PropTypes.object,
    PropTypes.func
  ]),
  Input: PropTypes.oneOf([
    PropTypes.object,
    PropTypes.func
  ])
}, 'overrides')

render(
  <Overrides Button={{color: 'blue'}} Input={() => <input type='tel' />}>
    <OverridableButton style={{background: 'yellow'}} />
    <OverridableInput />
  </Overrides>,
  document.getElementById('root')
)
```

If the override is set to be an object, it will be [deep merged](https://www.npmjs.com/package/deepmerge) with the props of the component with that display name. If the override is set to be a function, the component implementation will be replaced with that function.

**Comment by Kadrei** [comment]
Just an Implementation detail: 

We should beware of using deepmerge too often.  `shouldComponentUpdate` often relies on an strict equality (`===`)-checks (e.g. like in `PureComponent`), which will always return `false` after a new deepmerge (which creates a new object). So we should reuse the old merged objects when `context` and `props` did not change.

**Comment by Deschtex** [comment]
Would the second argument to `getContextualizer` be the property name in the context?

**Comment by xaviervia** [comment]
That is indeed. This is already supported https://github.com/xaviervia/react-context-props#putting-everything-from-the-contextualizer-into-a-single-prop

**Comment by Deschtex** [comment]
Aha, right. Didn't realize it already existed.

**Comment by xaviervia** [comment]
Well I forgot to document it, I added the documentation just to answer you :D
