### ISSUE TITLE
Revisit component naming approach

### ISSUE THREAD

**Issue by xaviervia** [klarna/higher-order-components#9]
Currently we are always setting the higher-order components to take the name from the original component and re expose it in the resulting component. The purpose was to make sure the resulting component provides a name that represents what it has inside, but it might be working poorly for React devtools.

See https://github.com/klarna/higher-order-components/pull/8#discussion_r96431077 for where the discussion started.

**Comment by xaviervia** [comment]
I line with this, we should probably rename all these higher-order components to better describe themselves. Here is the proposal we came up together with @pirelenito :

-  `notifyOnLowFPS` -> `withFPS` . Also change the API so that the passed prop is called `fps`, and the "handlers" are actually functions in an object prop called `fpsCollection` (`start()` and `stop()`)
- `deprecate` -> `withDeprecationWarning`
- `uniqueName` -> `withUniqueFormIdentifier`
- `overridable`: it's going to be split into two:
  - `withOverridableCSSModule` will provide the functionality of overriding the css module object passed down as a prop named `cssModule`.
  - `withOverridableComponent` will provide the functionality of replacing the component entirely by using another constructor set up in the React.context
- `themeable` -> `withTheme`. Also the `customizations` prop should be renamed to `theme`. The `<Theme>` component should put any props it receives within the `theme` prop in the context.
- `uncontrolled` -> `withUncontrolledPropAlternative` (since it adds an alternative version of the prop that is uncontrolled)
- `namespacedDisplayName ` -> the proposals are `withWrappedDisplayName` and `withNicelyNamedWrapper`, since what the higher-order component does is to provide a wrapper with the corresponding name rather than mutating the component with the new one.

**Comment by Nevon** [comment]
I like this suggestion! For the last one, I would propose `withPrefixedDisplayName`.

The `uncontrolled` one I'm not sure about. I feel like a good rule of thumb might be that the names should either be something like `withNoun` or `adjective`, but I can't think of a good name for this one.

**Comment by cskeppstedt** [comment]
A thought, `withFPS`, could it be `withFPSGauge` or something similar? Just "fps" doesn't tell me that much (also what does the `fps` prop contain?).

**Comment by xaviervia** [comment]
👍 we debated the "uncontrolled" with Paulo a specially long time and in particular the `withUncontrollableProp`: my feeling is that if I tell you that something is "uncontrollable" it means that there is no way to control it—so you can’t make it controlled using the original prop. 

I kind of like `withUncontrolledProp`. Adding the `Alternative` makes it more descriptive but you have to know what it does anyway to understand it and the "Alternative" part doesn’t help _too much_ with that.

@cskeppstedt: `fps` will contain just a number with the measured FPS. I guess adding `Gauge` or any other sort of clarification would actually help. I like the word `gauge`, it implies a specific kind of measuring that makes it more suggestive than just saying "FPS collection" of "FPS measuring". I don’t know for sure though, I can imagine there are other variations and some might be more specific.

@Nevon the `withPrefixedDisplayName` we were also considering changing it’s API a little bit. Right now every higher-order component in this repo puts the inner component’s name as `displayName` of the newly generated component, but that shouldn’t be so, because it obscures the component structure. That said, not doing that anymore implies that if we want to have nice names for components built with a higher-order component composition, we can really benefit from having a higher-order component that does just that—set the `displayName` prop in a new wrapper component. This changes the use case from just conveniently adding prefixes to display names to adding display names in general. I think that the adding prefix functionality is still valuable though, so I'm thinking about writing it so that it has this signature:

```haskell
withDisplayName :: String -> Component -> Component
```

…but if you keep passing strings to it, it just piles them up in namespaces:

```haskell
withDisplayName :: String -> String -> Component -> Component
withDisplayName :: String -> String -> String ->Component -> Component
```

For example from this you would get the name `Icon.Arrow.Left`

```javascript
withDisplayName('Icon')('Arrow')('Left')(LeftArrow)
```

**Comment by xaviervia** [comment]
Overridable will be addressed in https://github.com/klarna/higher-order-components/issues/25

**Comment by xaviervia** [comment]
`withFPSGauge` et al will be addressed in https://github.com/klarna/higher-order-components/issues/26

**Comment by xaviervia** [comment]
Closing in favor of #24
